- name: configure the login banner
  ios_banner:
    banner: motd
    text: |
      #########################################################
      this is my login banner
      that contains a multiline
      string
      #########################################################
    state: present
