---

- name: validate connection from R1
  ios_ping:
    dest: '{{ item }}'
    state: 'present'
  when: "'R1' in inventory_hostname"
  with_items:
    - '10.1.1.2'
    - '10.1.1.6'

- name: validate connection from R2
  ios_ping:
    dest: '{{ item }}'
    state: 'present'
  when: "'R2' in inventory_hostname"
  with_items:
    - '10.1.1.1'
    - '10.1.1.6'

- name: validate connection from R3
  ios_ping:
    dest: '{{ item }}'
    state: 'present'
  when: "'R3' in inventory_hostname"
  with_items:
    - '10.1.1.5'
    - '10.1.1.1'
